// pdfTheme.js
//
// Shared PDFKit drawing helpers so every PDF report generated by this app
// (the main inventory report and the BESCOM component report) looks like
// it came from the same product: same header band, same KPI cards, same
// table styling, same footer with page numbers. Nothing here talks to the
// database -- callers pass in plain data and this file only draws.

const COMPANY_NAME = process.env.COMPANY_NAME || "RoboManthan";
const COMPANY_LOGO_PATH = process.env.COMPANY_LOGO_PATH || "";

const COLORS = {
  headerBg: "#0f172a", // slate-900
  headerText: "#ffffff",
  headerSubtext: "#cbd5e1", // slate-300
  accent: "#2563eb", // blue-600
  text: "#1e293b", // slate-800
  muted: "#64748b", // slate-500
  border: "#e2e8f0", // slate-200
  tableHeaderBg: "#1e293b", // slate-800
  tableHeaderText: "#ffffff",
  rowAlt: "#f8fafc", // slate-50
  kpiBg: "#f1f5f9", // slate-100
  success: "#16a34a",
  warning: "#d97706",
  danger: "#dc2626",
};

const PAGE_MARGIN = 40;

function fmtDate(d) {
  if (!d) return "";
  const date = new Date(d);
  if (isNaN(date.getTime())) return "";
  return date.toLocaleString("en-IN", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function fmtDateOnly(d) {
  if (!d) return "";
  const date = new Date(d);
  if (isNaN(date.getTime())) return "";
  return date.toISOString().slice(0, 10);
}

/**
 * Draws the branded header band at the top of the current page.
 * Returns the y-coordinate immediately below the band.
 */
function drawHeader(doc, { title, subtitle, meta }) {
  const pageWidth = doc.page.width;
  const bandHeight = 92;

  doc.rect(0, 0, pageWidth, bandHeight).fill(COLORS.headerBg);

  let textX = PAGE_MARGIN;
  if (COMPANY_LOGO_PATH) {
    try {
      doc.image(COMPANY_LOGO_PATH, PAGE_MARGIN, 18, { width: 44, height: 44 });
      textX = PAGE_MARGIN + 56;
    } catch (e) {
      // fall through -- just skip the logo
    }
  }

  doc
    .fillColor(COLORS.headerText)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text(COMPANY_NAME.toUpperCase(), textX, 20, { characterSpacing: 1 });

  doc
    .fillColor(COLORS.headerText)
    .font("Helvetica-Bold")
    .fontSize(19)
    .text(title, textX, 36);

  if (subtitle) {
    doc
      .fillColor(COLORS.headerSubtext)
      .font("Helvetica")
      .fontSize(10)
      .text(subtitle, textX, 62);
  }

  if (meta) {
    doc
      .fillColor(COLORS.headerSubtext)
      .font("Helvetica")
      .fontSize(9)
      .text(meta, PAGE_MARGIN, bandHeight - 18, {
        width: pageWidth - PAGE_MARGIN * 2,
        align: "right",
      });
  }

  doc.fillColor(COLORS.text).font("Helvetica");
  return bandHeight + 20;
}

/**
 * Draws the footer (thin rule + "generated by" text + "Page X of Y") on
 * every buffered page. Requires the document to have been created with
 * `bufferPages: true`. Call this once, right before doc.end().
 */
function finalizeWithFooters(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const y = pageHeight - 40;

    doc
      .moveTo(PAGE_MARGIN, y)
      .lineTo(pageWidth - PAGE_MARGIN, y)
      .strokeColor(COLORS.border)
      .lineWidth(0.75)
      .stroke();

    doc
      .fillColor(COLORS.muted)
      .font("Helvetica")
      .fontSize(8)
      .text(`Generated by ${COMPANY_NAME} Inventory Management System`, PAGE_MARGIN, y + 8);

    doc
      .fillColor(COLORS.muted)
      .font("Helvetica")
      .fontSize(8)
      .text(`Page ${i + 1} of ${range.count}`, PAGE_MARGIN, y + 8, {
        width: pageWidth - PAGE_MARGIN * 2,
        align: "right",
      });

    doc.fillColor(COLORS.text).font("Helvetica");
  }
}

/**
 * Draws a row of KPI summary cards. `items` is an array of {label, value}.
 * Returns the y-coordinate below the cards.
 */
function drawKpiCards(doc, items, startY) {
  const pageWidth = doc.page.width;
  const usableWidth = pageWidth - PAGE_MARGIN * 2;
  const gap = 10;
  const cardWidth = (usableWidth - gap * (items.length - 1)) / items.length;
  const cardHeight = 54;

  items.forEach((item, i) => {
    const x = PAGE_MARGIN + i * (cardWidth + gap);
    doc
      .roundedRect(x, startY, cardWidth, cardHeight, 6)
      .fill(COLORS.kpiBg);
    doc
      .rect(x, startY, 3, cardHeight)
      .fill(COLORS.accent);
    doc
      .fillColor(COLORS.muted)
      .font("Helvetica")
      .fontSize(8)
      .text(item.label.toUpperCase(), x + 12, startY + 10, {
        width: cardWidth - 20,
        characterSpacing: 0.4,
      });
    doc
      .fillColor(COLORS.text)
      .font("Helvetica-Bold")
      .fontSize(18)
      .text(String(item.value), x + 12, startY + 24, { width: cardWidth - 20 });
  });

  doc.fillColor(COLORS.text).font("Helvetica");
  return startY + cardHeight + 24;
}

function sectionTitle(doc, title, y) {
  doc
    .fillColor(COLORS.text)
    .font("Helvetica-Bold")
    .fontSize(13)
    .text(title, PAGE_MARGIN, y);
  const lineY = y + 18;
  doc
    .moveTo(PAGE_MARGIN, lineY)
    .lineTo(doc.page.width - PAGE_MARGIN, lineY)
    .strokeColor(COLORS.accent)
    .lineWidth(1.5)
    .stroke();
  doc.fillColor(COLORS.text).font("Helvetica");
  return lineY + 14;
}

/**
 * Draws a bordered, shaded-header table starting at `startY`. Automatically
 * adds new pages (with the header band redrawn and column headers repeated)
 * when content runs past the bottom margin.
 *
 * columns: [{ header, key, width, align? }]
 * rows: array of plain objects keyed by column `key`
 * pageHeaderOpts: same shape as drawHeader()'s argument, used if the table
 *   spills onto a new page.
 */
function drawTable(doc, { columns, rows, startY, pageHeaderOpts, emptyText }) {
  const pageWidth = doc.page.width;
  const pageBottom = doc.page.height - 56;
  const tableX = PAGE_MARGIN;
  const tableWidth = pageWidth - PAGE_MARGIN * 2;

  // normalize column widths to fill tableWidth if not all specified
  const totalGiven = columns.reduce((s, c) => s + (c.width || 0), 0);
  const flexCols = columns.filter((c) => !c.width);
  const remaining = Math.max(tableWidth - totalGiven, 0);
  const flexWidth = flexCols.length ? remaining / flexCols.length : 0;
  const colWidths = columns.map((c) => c.width || flexWidth);

  const headerRowHeight = 22;
  const rowHeight = 20;

  function drawColumnHeaders(y) {
    doc.rect(tableX, y, tableWidth, headerRowHeight).fill(COLORS.tableHeaderBg);
    let x = tableX;
    columns.forEach((col, i) => {
      doc
        .fillColor(COLORS.tableHeaderText)
        .font("Helvetica-Bold")
        .fontSize(8.5)
        .text(col.header, x + 6, y + 7, {
          width: colWidths[i] - 10,
          align: col.align || "left",
        });
      x += colWidths[i];
    });
    doc.fillColor(COLORS.text).font("Helvetica");
    return y + headerRowHeight;
  }

  let y = startY;
  y = drawColumnHeaders(y);

  if (!rows || rows.length === 0) {
    doc
      .fillColor(COLORS.muted)
      .font("Helvetica-Oblique")
      .fontSize(9)
      .text(emptyText || "No data available.", tableX + 6, y + 8);
    doc.fillColor(COLORS.text).font("Helvetica");
    return y + rowHeight + 10;
  }

  rows.forEach((row, idx) => {
    if (y + rowHeight > pageBottom) {
      doc.addPage();
      let ny = PAGE_MARGIN;
      if (pageHeaderOpts) {
        ny = drawHeader(doc, pageHeaderOpts);
      }
      y = drawColumnHeaders(ny);
    }

    if (idx % 2 === 1) {
      doc.rect(tableX, y, tableWidth, rowHeight).fill(COLORS.rowAlt);
      doc.fillColor(COLORS.text);
    }

    let x = tableX;
    columns.forEach((col, i) => {
      const raw = row[col.key];
      const value = raw === null || raw === undefined || raw === "" ? "-" : String(raw);
      doc
        .fillColor(COLORS.text)
        .font("Helvetica")
        .fontSize(8.5)
        .text(value, x + 6, y + 6, {
          width: colWidths[i] - 10,
          align: col.align || "left",
          ellipsis: true,
        });
      x += colWidths[i];
    });

    doc
      .moveTo(tableX, y + rowHeight)
      .lineTo(tableX + tableWidth, y + rowHeight)
      .strokeColor(COLORS.border)
      .lineWidth(0.5)
      .stroke();

    y += rowHeight;
  });

  doc.fillColor(COLORS.text).font("Helvetica");
  return y + 20;
}

module.exports = {
  COLORS,
  COMPANY_NAME,
  PAGE_MARGIN,
  fmtDate,
  fmtDateOnly,
  drawHeader,
  finalizeWithFooters,
  drawKpiCards,
  sectionTitle,
  drawTable,
};
